# # Here is the cluster ip service config
# kind: Service
# apiVersion: v1
# metadata:
#   name: mongo-cluster-ip-service
# spec:
#   type: ClusterIP
#   ports:
#   - port: 27017
#     targetPort: 27017