const { v4 } = require('uuid')
import Api from '@/services/apiService'

export const state = () => ({
  devices: [
    {
      name: 'Cashier',
      printerName: 'Kitchen',
      paperSize: 'A4',
      printDocument: 'Order',
      printerStatus: true,
      copies: 5,
      printStation: 'Cashier',
      preview: 'Direct print',
    },
    {
      name: 'Cashier',
      printerName: 'Kitchen',
      paperSize: 'A4',
      printDocument: 'Order',
      printerStatus: true,
      copies: 5,
      printStation: 'Cashier',
      preview: 'Direct print',
    },
    {
      name: 'Cashier',
      printerName: 'Kitchen',
      paperSize: 'A4',
      printDocument: 'Order',
      printerStatus: true,
      copies: 5,
      printStation: 'Cashier',
      preview: 'Direct print',
    },
    {
      name: 'Cashier',
      printerName: 'Kitchen',
      paperSize: 'A4',
      printDocument: 'Order',
      printerStatus: true,
      copies: 5,
      printStation: 'Cashier',
      preview: 'Direct print',
    },
    {
      name: 'Cashier',
      printerName: 'Kitchen',
      paperSize: 'A4',
      printDocument: 'Order',
      printerStatus: true,
      copies: 5,
      printStation: 'Cashier',
      preview: 'Direct print',
    },
    {
      name: 'Restaurant',
      printerName: 'Bar',
      paperSize: 'A4',
      printDocument: 'Receipt',
      printerStatus: true,
      copies: 5,
      printStation: 'Cashier',
      preview: 'Direct print',
    },
    {
      name: 'Restaurant',
      printerName: 'Bar',
      paperSize: 'A4',
      printDocument: 'Receipt',
      printerStatus: true,
      copies: 5,
      printStation: 'Cashier',
      preview: 'Direct print',
    },
    {
      name: 'Restaurant',
      printerName: 'Bar',
      paperSize: 'A4',
      printDocument: 'Receipt',
      printerStatus: true,
      copies: 5,
      printStation: 'Cashier',
      preview: 'Direct print',
    },
    {
      name: 'Restaurant',
      printerName: 'Bar',
      paperSize: 'A4',
      printDocument: 'Receipt',
      printerStatus: true,
      copies: 5,
      printStation: 'Cashier',
      preview: 'Direct print',
    },
    {
      name: 'Restaurant',
      printerName: 'Bar',
      paperSize: 'A4',
      printDocument: 'Receipt',
      printerStatus: true,
      copies: 5,
      printStation: 'Cashier',
      preview: 'Direct print',
    },
  ],
})
export const getters = {}
export const actions = {
  devices: (store: any) => store.devices,
}
